#!/usr/bin/env bash
# install-python-deps

source version.sh

python3 -m venv env
source env/bin/activate
pip3 install pip --upgrade
pip3 install jsonschema==${JSONSCHEMA_VERSION} openskill==${OPENSKILL_VERSION}
